### ISSUE TITLE
Problem playing

### ISSUE THREAD

**Issue by slithertheman** [sealldeveloper/FlipperSkylanders#1]
after like 6 seconds it loads the skylander back in as if i just removed it and placed it back on the portal

**Comment by sealldeveloper** [comment]
I think theres something a bit wrong with these files atm, ill fix when i can

**Comment by Loule95450** [comment]
up :)

**Comment by sealldeveloper** [comment]
Gday, from what I'm aware the way the Flipper emulates isn't recognised as a Skylander, this is more a Flipper file format version of Skylanders for writing to magic tags, which ive found works well.

I'll take a look into emulation but I think the way the Flipper emulates is recognised as an invalid Skylander by the Portal.

**Comment by AlePiton** [comment]
so to get these to work properly, you need to buy some magic tags, write the skylanders onto them, then use the magic tags on the portal?

**Comment by sealldeveloper** [comment]
> so to get these to work properly, you need to buy some magic tags, write the skylanders onto them, then use the magic tags on the portal?

Yep
